// Generated by gencpp from file ros_stairsdetection/ClearStairsRequest.msg
// DO NOT EDIT!


#ifndef ROS_STAIRSDETECTION_MESSAGE_CLEARSTAIRSREQUEST_H
#define ROS_STAIRSDETECTION_MESSAGE_CLEARSTAIRSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_stairsdetection
{
template <class ContainerAllocator>
struct ClearStairsRequest_
{
  typedef ClearStairsRequest_<ContainerAllocator> Type;

  ClearStairsRequest_()
    {
    }
  ClearStairsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ClearStairsRequest_

typedef ::ros_stairsdetection::ClearStairsRequest_<std::allocator<void> > ClearStairsRequest;

typedef boost::shared_ptr< ::ros_stairsdetection::ClearStairsRequest > ClearStairsRequestPtr;
typedef boost::shared_ptr< ::ros_stairsdetection::ClearStairsRequest const> ClearStairsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace ros_stairsdetection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_stairsdetection/ClearStairsRequest";
  }

  static const char* value(const ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClearStairsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ros_stairsdetection::ClearStairsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROS_STAIRSDETECTION_MESSAGE_CLEARSTAIRSREQUEST_H
