// Generated by gencpp from file ros_stairsdetection/ClearStairs.msg
// DO NOT EDIT!


#ifndef ROS_STAIRSDETECTION_MESSAGE_CLEARSTAIRS_H
#define ROS_STAIRSDETECTION_MESSAGE_CLEARSTAIRS_H

#include <ros/service_traits.h>


#include <ros_stairsdetection/ClearStairsRequest.h>
#include <ros_stairsdetection/ClearStairsResponse.h>


namespace ros_stairsdetection
{

struct ClearStairs
{

typedef ClearStairsRequest Request;
typedef ClearStairsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearStairs
} // namespace ros_stairsdetection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_stairsdetection::ClearStairs > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ros_stairsdetection::ClearStairs&) { return value(); }
};

template<>
struct DataType< ::ros_stairsdetection::ClearStairs > {
  static const char* value()
  {
    return "ros_stairsdetection/ClearStairs";
  }

  static const char* value(const ::ros_stairsdetection::ClearStairs&) { return value(); }
};


// service_traits::MD5Sum< ::ros_stairsdetection::ClearStairsRequest> should match
// service_traits::MD5Sum< ::ros_stairsdetection::ClearStairs >
template<>
struct MD5Sum< ::ros_stairsdetection::ClearStairsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_stairsdetection::ClearStairs >::value();
  }
  static const char* value(const ::ros_stairsdetection::ClearStairsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_stairsdetection::ClearStairsRequest> should match
// service_traits::DataType< ::ros_stairsdetection::ClearStairs >
template<>
struct DataType< ::ros_stairsdetection::ClearStairsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_stairsdetection::ClearStairs >::value();
  }
  static const char* value(const ::ros_stairsdetection::ClearStairsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_stairsdetection::ClearStairsResponse> should match
// service_traits::MD5Sum< ::ros_stairsdetection::ClearStairs >
template<>
struct MD5Sum< ::ros_stairsdetection::ClearStairsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_stairsdetection::ClearStairs >::value();
  }
  static const char* value(const ::ros_stairsdetection::ClearStairsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_stairsdetection::ClearStairsResponse> should match
// service_traits::DataType< ::ros_stairsdetection::ClearStairs >
template<>
struct DataType< ::ros_stairsdetection::ClearStairsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_stairsdetection::ClearStairs >::value();
  }
  static const char* value(const ::ros_stairsdetection::ClearStairsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_STAIRSDETECTION_MESSAGE_CLEARSTAIRS_H
