// Generated by gencpp from file ros_stairsdetection/ExportStairsRequest.msg
// DO NOT EDIT!


#ifndef ROS_STAIRSDETECTION_MESSAGE_EXPORTSTAIRSREQUEST_H
#define ROS_STAIRSDETECTION_MESSAGE_EXPORTSTAIRSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_stairsdetection
{
template <class ContainerAllocator>
struct ExportStairsRequest_
{
  typedef ExportStairsRequest_<ContainerAllocator> Type;

  ExportStairsRequest_()
    : path()  {
    }
  ExportStairsRequest_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExportStairsRequest_

typedef ::ros_stairsdetection::ExportStairsRequest_<std::allocator<void> > ExportStairsRequest;

typedef boost::shared_ptr< ::ros_stairsdetection::ExportStairsRequest > ExportStairsRequestPtr;
typedef boost::shared_ptr< ::ros_stairsdetection::ExportStairsRequest const> ExportStairsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator1> & lhs, const ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator1> & lhs, const ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_stairsdetection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d00cd540af97efeb6b1589112fab63e";
  }

  static const char* value(const ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d00cd540af97efeULL;
  static const uint64_t static_value2 = 0xb6b1589112fab63eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_stairsdetection/ExportStairsRequest";
  }

  static const char* value(const ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string path\n"
;
  }

  static const char* value(const ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExportStairsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_stairsdetection::ExportStairsRequest_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_STAIRSDETECTION_MESSAGE_EXPORTSTAIRSREQUEST_H
