// Generated by gencpp from file ros_stairsdetection/ExportStairs.msg
// DO NOT EDIT!


#ifndef ROS_STAIRSDETECTION_MESSAGE_EXPORTSTAIRS_H
#define ROS_STAIRSDETECTION_MESSAGE_EXPORTSTAIRS_H

#include <ros/service_traits.h>


#include <ros_stairsdetection/ExportStairsRequest.h>
#include <ros_stairsdetection/ExportStairsResponse.h>


namespace ros_stairsdetection
{

struct ExportStairs
{

typedef ExportStairsRequest Request;
typedef ExportStairsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExportStairs
} // namespace ros_stairsdetection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_stairsdetection::ExportStairs > {
  static const char* value()
  {
    return "b232266867e934f58d024196cb4b3a8d";
  }

  static const char* value(const ::ros_stairsdetection::ExportStairs&) { return value(); }
};

template<>
struct DataType< ::ros_stairsdetection::ExportStairs > {
  static const char* value()
  {
    return "ros_stairsdetection/ExportStairs";
  }

  static const char* value(const ::ros_stairsdetection::ExportStairs&) { return value(); }
};


// service_traits::MD5Sum< ::ros_stairsdetection::ExportStairsRequest> should match
// service_traits::MD5Sum< ::ros_stairsdetection::ExportStairs >
template<>
struct MD5Sum< ::ros_stairsdetection::ExportStairsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_stairsdetection::ExportStairs >::value();
  }
  static const char* value(const ::ros_stairsdetection::ExportStairsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_stairsdetection::ExportStairsRequest> should match
// service_traits::DataType< ::ros_stairsdetection::ExportStairs >
template<>
struct DataType< ::ros_stairsdetection::ExportStairsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_stairsdetection::ExportStairs >::value();
  }
  static const char* value(const ::ros_stairsdetection::ExportStairsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_stairsdetection::ExportStairsResponse> should match
// service_traits::MD5Sum< ::ros_stairsdetection::ExportStairs >
template<>
struct MD5Sum< ::ros_stairsdetection::ExportStairsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_stairsdetection::ExportStairs >::value();
  }
  static const char* value(const ::ros_stairsdetection::ExportStairsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_stairsdetection::ExportStairsResponse> should match
// service_traits::DataType< ::ros_stairsdetection::ExportStairs >
template<>
struct DataType< ::ros_stairsdetection::ExportStairsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_stairsdetection::ExportStairs >::value();
  }
  static const char* value(const ::ros_stairsdetection::ExportStairsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_STAIRSDETECTION_MESSAGE_EXPORTSTAIRS_H
