// Generated by gencpp from file ros_stairsdetection/ExportStairsResponse.msg
// DO NOT EDIT!


#ifndef ROS_STAIRSDETECTION_MESSAGE_EXPORTSTAIRSRESPONSE_H
#define ROS_STAIRSDETECTION_MESSAGE_EXPORTSTAIRSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_stairsdetection
{
template <class ContainerAllocator>
struct ExportStairsResponse_
{
  typedef ExportStairsResponse_<ContainerAllocator> Type;

  ExportStairsResponse_()
    : result()  {
    }
  ExportStairsResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ExportStairsResponse_

typedef ::ros_stairsdetection::ExportStairsResponse_<std::allocator<void> > ExportStairsResponse;

typedef boost::shared_ptr< ::ros_stairsdetection::ExportStairsResponse > ExportStairsResponsePtr;
typedef boost::shared_ptr< ::ros_stairsdetection::ExportStairsResponse const> ExportStairsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator1> & lhs, const ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator1> & lhs, const ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_stairsdetection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_stairsdetection/ExportStairsResponse";
  }

  static const char* value(const ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"\n"
;
  }

  static const char* value(const ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExportStairsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_stairsdetection::ExportStairsResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_STAIRSDETECTION_MESSAGE_EXPORTSTAIRSRESPONSE_H
