// Generated by gencpp from file ros_stairsdetection/ImportStairs.msg
// DO NOT EDIT!


#ifndef ROS_STAIRSDETECTION_MESSAGE_IMPORTSTAIRS_H
#define ROS_STAIRSDETECTION_MESSAGE_IMPORTSTAIRS_H

#include <ros/service_traits.h>


#include <ros_stairsdetection/ImportStairsRequest.h>
#include <ros_stairsdetection/ImportStairsResponse.h>


namespace ros_stairsdetection
{

struct ImportStairs
{

typedef ImportStairsRequest Request;
typedef ImportStairsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImportStairs
} // namespace ros_stairsdetection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_stairsdetection::ImportStairs > {
  static const char* value()
  {
    return "b232266867e934f58d024196cb4b3a8d";
  }

  static const char* value(const ::ros_stairsdetection::ImportStairs&) { return value(); }
};

template<>
struct DataType< ::ros_stairsdetection::ImportStairs > {
  static const char* value()
  {
    return "ros_stairsdetection/ImportStairs";
  }

  static const char* value(const ::ros_stairsdetection::ImportStairs&) { return value(); }
};


// service_traits::MD5Sum< ::ros_stairsdetection::ImportStairsRequest> should match
// service_traits::MD5Sum< ::ros_stairsdetection::ImportStairs >
template<>
struct MD5Sum< ::ros_stairsdetection::ImportStairsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_stairsdetection::ImportStairs >::value();
  }
  static const char* value(const ::ros_stairsdetection::ImportStairsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_stairsdetection::ImportStairsRequest> should match
// service_traits::DataType< ::ros_stairsdetection::ImportStairs >
template<>
struct DataType< ::ros_stairsdetection::ImportStairsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_stairsdetection::ImportStairs >::value();
  }
  static const char* value(const ::ros_stairsdetection::ImportStairsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_stairsdetection::ImportStairsResponse> should match
// service_traits::MD5Sum< ::ros_stairsdetection::ImportStairs >
template<>
struct MD5Sum< ::ros_stairsdetection::ImportStairsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_stairsdetection::ImportStairs >::value();
  }
  static const char* value(const ::ros_stairsdetection::ImportStairsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_stairsdetection::ImportStairsResponse> should match
// service_traits::DataType< ::ros_stairsdetection::ImportStairs >
template<>
struct DataType< ::ros_stairsdetection::ImportStairsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_stairsdetection::ImportStairs >::value();
  }
  static const char* value(const ::ros_stairsdetection::ImportStairsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_STAIRSDETECTION_MESSAGE_IMPORTSTAIRS_H
