(cl:defpackage ros_stairsdetection-srv
  (:use )
  (:export
   "CLEARSTAIRS"
   "<CLEARSTAIRS-REQUEST>"
   "CLEARSTAIRS-REQUEST"
   "<CLEARSTAIRS-RESPONSE>"
   "CLEARSTAIRS-RESPONSE"
   "EXPORTSTAIRS"
   "<EXPORTSTAIRS-REQUEST>"
   "EXPORTSTAIRS-REQUEST"
   "<EXPORTSTAIRS-RESPONSE>"
   "EXPORTSTAIRS-RESPONSE"
   "IMPORTSTAIRS"
   "<IMPORTSTAIRS-REQUEST>"
   "IMPORTSTAIRS-REQUEST"
   "<IMPORTSTAIRS-RESPONSE>"
   "IMPORTSTAIRS-RESPONSE"
  ))

