//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the stairdetection package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __stairdetection__STAIRDETECTIONCONFIG_H__
#define __stairdetection__STAIRDETECTIONCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace stairdetection
{
  class stairdetectionConfigStatics;

  class stairdetectionConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(stairdetectionConfig &config, const stairdetectionConfig &max, const stairdetectionConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const stairdetectionConfig &config1, const stairdetectionConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, stairdetectionConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const stairdetectionConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, stairdetectionConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const stairdetectionConfig &config) const = 0;
      virtual void getValue(const stairdetectionConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T stairdetectionConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T stairdetectionConfig::* field;

      virtual void clamp(stairdetectionConfig &config, const stairdetectionConfig &max, const stairdetectionConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const stairdetectionConfig &config1, const stairdetectionConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, stairdetectionConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const stairdetectionConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, stairdetectionConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const stairdetectionConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const stairdetectionConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, stairdetectionConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, stairdetectionConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<stairdetectionConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(stairdetectionConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("leafsize"==(*_i)->name){leafsize = boost::any_cast<double>(val);}
        if("window_size"==(*_i)->name){window_size = boost::any_cast<double>(val);}
        if("z_min_filter"==(*_i)->name){z_min_filter = boost::any_cast<double>(val);}
        if("z_max_filter"==(*_i)->name){z_max_filter = boost::any_cast<double>(val);}
        if("z_division_size"==(*_i)->name){z_division_size = boost::any_cast<double>(val);}
        if("angle_divisions"==(*_i)->name){angle_divisions = boost::any_cast<int>(val);}
        if("bearing_var"==(*_i)->name){bearing_var = boost::any_cast<double>(val);}
        if("range_var"==(*_i)->name){range_var = boost::any_cast<double>(val);}
        if("least_sq_angle_thresh"==(*_i)->name){least_sq_angle_thresh = boost::any_cast<double>(val);}
        if("least_sq_radius_thresh"==(*_i)->name){least_sq_radius_thresh = boost::any_cast<double>(val);}
        if("max_line_gap"==(*_i)->name){max_line_gap = boost::any_cast<double>(val);}
        if("min_line_length"==(*_i)->name){min_line_length = boost::any_cast<double>(val);}
        if("min_range"==(*_i)->name){min_range = boost::any_cast<double>(val);}
        if("max_range"==(*_i)->name){max_range = boost::any_cast<double>(val);}
        if("min_split_dist"==(*_i)->name){min_split_dist = boost::any_cast<double>(val);}
        if("outlier_dist"==(*_i)->name){outlier_dist = boost::any_cast<double>(val);}
        if("min_line_points"==(*_i)->name){min_line_points = boost::any_cast<int>(val);}
        if("min_height"==(*_i)->name){min_height = boost::any_cast<double>(val);}
        if("max_height"==(*_i)->name){max_height = boost::any_cast<double>(val);}
        if("min_depth"==(*_i)->name){min_depth = boost::any_cast<double>(val);}
        if("max_depth"==(*_i)->name){max_depth = boost::any_cast<double>(val);}
        if("min_slope"==(*_i)->name){min_slope = boost::any_cast<double>(val);}
        if("max_slope"==(*_i)->name){max_slope = boost::any_cast<double>(val);}
        if("max_orientation_diff"==(*_i)->name){max_orientation_diff = boost::any_cast<double>(val);}
        if("min_offset_angle"==(*_i)->name){min_offset_angle = boost::any_cast<double>(val);}
        if("max_offset_angle"==(*_i)->name){max_offset_angle = boost::any_cast<double>(val);}
        if("nr_steps"==(*_i)->name){nr_steps = boost::any_cast<int>(val);}
      }
    }

    double leafsize;
double window_size;
double z_min_filter;
double z_max_filter;
double z_division_size;
int angle_divisions;
double bearing_var;
double range_var;
double least_sq_angle_thresh;
double least_sq_radius_thresh;
double max_line_gap;
double min_line_length;
double min_range;
double max_range;
double min_split_dist;
double outlier_dist;
int min_line_points;
double min_height;
double max_height;
double min_depth;
double max_depth;
double min_slope;
double max_slope;
double max_orientation_diff;
double min_offset_angle;
double max_offset_angle;
int nr_steps;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double leafsize;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double window_size;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double z_min_filter;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double z_max_filter;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double z_division_size;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int angle_divisions;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double bearing_var;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double range_var;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double least_sq_angle_thresh;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double least_sq_radius_thresh;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_line_gap;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_line_length;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_range;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_range;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_split_dist;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double outlier_dist;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_line_points;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_height;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_height;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_depth;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_depth;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_slope;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_slope;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_orientation_diff;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_offset_angle;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_offset_angle;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int nr_steps;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("stairdetectionConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const stairdetectionConfig &__max__ = __getMax__();
      const stairdetectionConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const stairdetectionConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const stairdetectionConfig &__getDefault__();
    static const stairdetectionConfig &__getMax__();
    static const stairdetectionConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const stairdetectionConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void stairdetectionConfig::ParamDescription<std::string>::clamp(stairdetectionConfig &config, const stairdetectionConfig &max, const stairdetectionConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class stairdetectionConfigStatics
  {
    friend class stairdetectionConfig;

    stairdetectionConfigStatics()
    {
stairdetectionConfig::GroupDescription<stairdetectionConfig::DEFAULT, stairdetectionConfig> Default("Default", "", 0, 0, true, &stairdetectionConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.leafsize = 0.01;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.leafsize = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.leafsize = 0.04;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("leafsize", "double", 0, "Sampling leafsize", "", &stairdetectionConfig::leafsize)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("leafsize", "double", 0, "Sampling leafsize", "", &stairdetectionConfig::leafsize)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.window_size = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.window_size = 3.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.window_size = 2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("window_size", "double", 0, "Window of plane extraction", "", &stairdetectionConfig::window_size)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("window_size", "double", 0, "Window of plane extraction", "", &stairdetectionConfig::window_size)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.z_min_filter = -5.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.z_min_filter = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.z_min_filter = -2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("z_min_filter", "double", 0, "min value at z axis for plane extraction", "", &stairdetectionConfig::z_min_filter)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("z_min_filter", "double", 0, "min value at z axis for plane extraction", "", &stairdetectionConfig::z_min_filter)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.z_max_filter = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.z_max_filter = 5.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.z_max_filter = 2.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("z_max_filter", "double", 0, "max value at z axis for plane extraction", "", &stairdetectionConfig::z_max_filter)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("z_max_filter", "double", 0, "max value at z axis for plane extraction", "", &stairdetectionConfig::z_max_filter)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.z_division_size = 0.01;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.z_division_size = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.z_division_size = 0.1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("z_division_size", "double", 0, "height of z division cell size", "", &stairdetectionConfig::z_division_size)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("z_division_size", "double", 0, "height of z division cell size", "", &stairdetectionConfig::z_division_size)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.angle_divisions = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.angle_divisions = 360;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.angle_divisions = 120;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<int>("angle_divisions", "int", 0, "number of how many subspaces azimuth angles are discretized", "", &stairdetectionConfig::angle_divisions)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<int>("angle_divisions", "int", 0, "number of how many subspaces azimuth angles are discretized", "", &stairdetectionConfig::angle_divisions)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.bearing_var = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.bearing_var = 0.0001;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.bearing_var = 1e-06;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("bearing_var", "double", 0, "bearing varicance", "", &stairdetectionConfig::bearing_var)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("bearing_var", "double", 0, "bearing varicance", "", &stairdetectionConfig::bearing_var)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.range_var = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.range_var = 0.01;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.range_var = 0.0004;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("range_var", "double", 0, "range variance", "", &stairdetectionConfig::range_var)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("range_var", "double", 0, "range variance", "", &stairdetectionConfig::range_var)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.least_sq_angle_thresh = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.least_sq_angle_thresh = 0.01;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.least_sq_angle_thresh = 0.0001;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("least_sq_angle_thresh", "double", 0, "least square threshold for angle", "", &stairdetectionConfig::least_sq_angle_thresh)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("least_sq_angle_thresh", "double", 0, "least square threshold for angle", "", &stairdetectionConfig::least_sq_angle_thresh)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.least_sq_radius_thresh = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.least_sq_radius_thresh = 0.01;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.least_sq_radius_thresh = 0.0001;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("least_sq_radius_thresh", "double", 0, "least square threshold for radius", "", &stairdetectionConfig::least_sq_radius_thresh)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("least_sq_radius_thresh", "double", 0, "least square threshold for radius", "", &stairdetectionConfig::least_sq_radius_thresh)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_line_gap = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_line_gap = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_line_gap = 0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_line_gap", "double", 0, "maximal allowed value for gaps in line detection", "", &stairdetectionConfig::max_line_gap)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_line_gap", "double", 0, "maximal allowed value for gaps in line detection", "", &stairdetectionConfig::max_line_gap)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_line_length = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_line_length = 3.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_line_length = 0.6;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_line_length", "double", 0, "minimal allowed value for line length", "", &stairdetectionConfig::min_line_length)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_line_length", "double", 0, "minimal allowed value for line length", "", &stairdetectionConfig::min_line_length)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_range = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_range = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_range = 0.4;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_range", "double", 0, "minimal allow value for distance of point from origin", "", &stairdetectionConfig::min_range)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_range", "double", 0, "minimal allow value for distance of point from origin", "", &stairdetectionConfig::min_range)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_range = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_range = 1000000.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_range = 9999.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_range", "double", 0, "maximal allowed value for distance of point from origin", "", &stairdetectionConfig::max_range)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_range", "double", 0, "maximal allowed value for distance of point from origin", "", &stairdetectionConfig::max_range)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_split_dist = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_split_dist = 0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_split_dist = 0.05;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_split_dist", "double", 0, "minimal allowed value for splitting line", "", &stairdetectionConfig::min_split_dist)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_split_dist", "double", 0, "minimal allowed value for splitting line", "", &stairdetectionConfig::min_split_dist)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.outlier_dist = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.outlier_dist = 0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.outlier_dist = 0.05;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("outlier_dist", "double", 0, "maximal allowed value for points to be considered inliers", "", &stairdetectionConfig::outlier_dist)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("outlier_dist", "double", 0, "maximal allowed value for points to be considered inliers", "", &stairdetectionConfig::outlier_dist)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_line_points = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_line_points = 20;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_line_points = 7;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<int>("min_line_points", "int", 0, "minimal allowed value for detecting a line", "", &stairdetectionConfig::min_line_points)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<int>("min_line_points", "int", 0, "minimal allowed value for detecting a line", "", &stairdetectionConfig::min_line_points)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_height = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_height = 0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_height = 0.11;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_height", "double", 0, "minimal allowed value for step height", "", &stairdetectionConfig::min_height)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_height", "double", 0, "minimal allowed value for step height", "", &stairdetectionConfig::min_height)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_height = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_height = 0.5;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_height = 0.3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_height", "double", 0, "maximal allowed value for step height", "", &stairdetectionConfig::max_height)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_height", "double", 0, "maximal allowed value for step height", "", &stairdetectionConfig::max_height)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_depth = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_depth = 0.6;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_depth = 0.15;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_depth", "double", 0, "minimal allowed value for step depth", "", &stairdetectionConfig::min_depth)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_depth", "double", 0, "minimal allowed value for step depth", "", &stairdetectionConfig::min_depth)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_depth = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_depth = 0.6;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_depth = 0.45;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_depth", "double", 0, "maximal allowed value for step depth", "", &stairdetectionConfig::max_depth)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_depth", "double", 0, "maximal allowed value for step depth", "", &stairdetectionConfig::max_depth)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_slope = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_slope = 90.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_slope = 25.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_slope", "double", 0, "minimal allowed value for step slope", "", &stairdetectionConfig::min_slope)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_slope", "double", 0, "minimal allowed value for step slope", "", &stairdetectionConfig::min_slope)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_slope = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_slope = 90.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_slope = 60.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_slope", "double", 0, "maximal allowed value for step slope", "", &stairdetectionConfig::max_slope)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_slope", "double", 0, "maximal allowed value for step slope", "", &stairdetectionConfig::max_slope)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_orientation_diff = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_orientation_diff = 20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_orientation_diff = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_orientation_diff", "double", 0, "maximal allowed value for orientation diff between steps", "", &stairdetectionConfig::max_orientation_diff)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_orientation_diff", "double", 0, "maximal allowed value for orientation diff between steps", "", &stairdetectionConfig::max_orientation_diff)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_offset_angle = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_offset_angle = 180.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_offset_angle = 60.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_offset_angle", "double", 0, "minimal allowed value for step offset angle", "", &stairdetectionConfig::min_offset_angle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("min_offset_angle", "double", 0, "minimal allowed value for step offset angle", "", &stairdetectionConfig::min_offset_angle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_offset_angle = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_offset_angle = 180.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_offset_angle = 120.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_offset_angle", "double", 0, "maximal allowed value for step offset angle", "", &stairdetectionConfig::max_offset_angle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<double>("max_offset_angle", "double", 0, "maximal allowed value for step offset angle", "", &stairdetectionConfig::max_offset_angle)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.nr_steps = 2;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.nr_steps = 10;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.nr_steps = 3;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<int>("nr_steps", "int", 0, "number of steps to detect staircase", "", &stairdetectionConfig::nr_steps)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(stairdetectionConfig::AbstractParamDescriptionConstPtr(new stairdetectionConfig::ParamDescription<int>("nr_steps", "int", 0, "number of steps to detect staircase", "", &stairdetectionConfig::nr_steps)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(stairdetectionConfig::AbstractGroupDescriptionConstPtr(new stairdetectionConfig::GroupDescription<stairdetectionConfig::DEFAULT, stairdetectionConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<stairdetectionConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<stairdetectionConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<stairdetectionConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    stairdetectionConfig __max__;
    stairdetectionConfig __min__;
    stairdetectionConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const stairdetectionConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static stairdetectionConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &stairdetectionConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const stairdetectionConfig &stairdetectionConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const stairdetectionConfig &stairdetectionConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const stairdetectionConfig &stairdetectionConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<stairdetectionConfig::AbstractParamDescriptionConstPtr> &stairdetectionConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<stairdetectionConfig::AbstractGroupDescriptionConstPtr> &stairdetectionConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const stairdetectionConfigStatics *stairdetectionConfig::__get_statics__()
  {
    const static stairdetectionConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = stairdetectionConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __STAIRDETECTIONRECONFIGURATOR_H__
