// Generated by gencpp from file stairdetection/Staircase.msg
// DO NOT EDIT!


#ifndef STAIRDETECTION_MESSAGE_STAIRCASE_H
#define STAIRDETECTION_MESSAGE_STAIRCASE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Vector3.h>

namespace stairdetection
{
template <class ContainerAllocator>
struct Staircase_
{
  typedef Staircase_<ContainerAllocator> Type;

  Staircase_()
    : type(0)
    , id(0)
    , width(0.0)
    , height(0.0)
    , depth(0.0)
    , nr_steps(0)
    , start_pose()
    , going_vector()  {
    }
  Staircase_(const ContainerAllocator& _alloc)
    : type(0)
    , id(0)
    , width(0.0)
    , height(0.0)
    , depth(0.0)
    , nr_steps(0)
    , start_pose(_alloc)
    , going_vector(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _type_type;
  _type_type type;

   typedef int32_t _id_type;
  _id_type id;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef float _depth_type;
  _depth_type depth;

   typedef int32_t _nr_steps_type;
  _nr_steps_type nr_steps;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _start_pose_type;
  _start_pose_type start_pose;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _going_vector_type;
  _going_vector_type going_vector;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ASCENDING)
  #undef ASCENDING
#endif
#if defined(_WIN32) && defined(DESCENDING)
  #undef DESCENDING
#endif

  enum {
    ASCENDING = 0u,
    DESCENDING = 1u,
  };


  typedef boost::shared_ptr< ::stairdetection::Staircase_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stairdetection::Staircase_<ContainerAllocator> const> ConstPtr;

}; // struct Staircase_

typedef ::stairdetection::Staircase_<std::allocator<void> > Staircase;

typedef boost::shared_ptr< ::stairdetection::Staircase > StaircasePtr;
typedef boost::shared_ptr< ::stairdetection::Staircase const> StaircaseConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stairdetection::Staircase_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stairdetection::Staircase_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stairdetection::Staircase_<ContainerAllocator1> & lhs, const ::stairdetection::Staircase_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.id == rhs.id &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.depth == rhs.depth &&
    lhs.nr_steps == rhs.nr_steps &&
    lhs.start_pose == rhs.start_pose &&
    lhs.going_vector == rhs.going_vector;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stairdetection::Staircase_<ContainerAllocator1> & lhs, const ::stairdetection::Staircase_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stairdetection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stairdetection::Staircase_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stairdetection::Staircase_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stairdetection::Staircase_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stairdetection::Staircase_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stairdetection::Staircase_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stairdetection::Staircase_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stairdetection::Staircase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "328f707a0f226253d43b60994d17c07a";
  }

  static const char* value(const ::stairdetection::Staircase_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x328f707a0f226253ULL;
  static const uint64_t static_value2 = 0xd43b60994d17c07aULL;
};

template<class ContainerAllocator>
struct DataType< ::stairdetection::Staircase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stairdetection/Staircase";
  }

  static const char* value(const ::stairdetection::Staircase_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stairdetection::Staircase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ASCENDING=0\n"
"uint8 DESCENDING=1\n"
"\n"
"int32 type\n"
"int32 id\n"
"float32 width\n"
"float32 height\n"
"float32 depth\n"
"int32 nr_steps\n"
"geometry_msgs/Pose start_pose\n"
"geometry_msgs/Vector3 going_vector\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::stairdetection::Staircase_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stairdetection::Staircase_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.id);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.depth);
      stream.next(m.nr_steps);
      stream.next(m.start_pose);
      stream.next(m.going_vector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Staircase_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stairdetection::Staircase_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stairdetection::Staircase_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
    s << indent << "nr_steps: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nr_steps);
    s << indent << "start_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.start_pose);
    s << indent << "going_vector: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.going_vector);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STAIRDETECTION_MESSAGE_STAIRCASE_H
